<?php

namespace App\Services\General\Payment\SyriatelCash;

use App\Services\Admin\Section\SectionService;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use App\Models\PaymentTransaction;
use Illuminate\Support\Facades\Crypt;
use RateLimiter;
use function GuzzleHttp\json_encode;

class SyriatelCashService
{

    protected string $merchantMSISDN;

    public function __construct(protected SectionService $sectionService)
    {
        $this->merchantMSISDN = env('SYRIATEL_MERCHANT_MSISDN', '');
    }


    public function getAllTransactions()
    {
        $transactions = PaymentTransaction::with(['user', 'section', 'coupon'])
            ->where('status', PaymentTransaction::SUCCESS_STATUS);
        if ($phoneNumber = request()->input('phone_number')) {
            $transactions->where('phone_number', $phoneNumber);
        }
        if ($sectionId = request()->input('section_id')) {
            $transactions->where('section_id', $sectionId);
        }
        if ($studentId = request()->input('student_id')) {
            $transactions->where('user_id', $studentId);
        }
        return $transactions->paginate(config('app.pagination_limit'));
    }

    /**
     * Initiates a payment transaction by:
     * - Generating a unique transaction ID
     * - Creating a PaymentTransaction record
     * - Sending the OTP request to SyriatelCash (using the external API)
     *
     * @param  array $data  Expected keys: user_id, phone_number, section_id, [coupon_id], amount
     * @return array        Returns ['transaction_id' => ..., 'provider_response' => ...]
     * @throws \Exception
     */
    public function initiatePaymentTransaction(array $data): array
    {
        if ($data['total_amount'] == 0) {
            $this->sectionService->open($data['section_id'], $data['user_id']);
            return [
                'subscribed' => true
            ];
        }
        do {
            $transactionId = (string) Str::uuid();
        } while (PaymentTransaction::where('transaction_id', $transactionId)->exists());
        $transaction = PaymentTransaction::create(array_merge([
            'transaction_id' => $transactionId,
        ], $data));





        $responseData = $this->sendSyriatelCashOTP($data['phone_number'], $transaction, $data['total_amount']);


        return [
            'transaction_id' => $transactionId,
            'provider_response' => $responseData,
        ];
    }

    /**
     * Confirms the payment by verifying the OTP.
     * On successful verification, updates the transaction record.
     *
     * @param  string           $otp
     * @param  string           $transactionId
     * @param  \App\Models\User $user  The authenticated user model instance.
     * @return array                   Returns a success message.
     * @throws \Exception
     */
    public function confirmPaymentTransaction(string $otp, $transaction, $viaCron = false)
    {
        if (!$viaCron)
            $transaction->update([
                'otp' => Crypt::encryptString($otp), // im saving it to ensure that the syriatel response returned with any network issue to retry it later via cron job , 
            ]);

        if (!$transaction) {
            throw new \Exception("Transaction not found.");
        }
        $responseData = $this->checkSyriatelCashOTP($otp, $transaction, $viaCron);
        if (isset($responseData['errorCode']) && $responseData['errorCode'] === '0') {
            $this->sectionService->open($transaction->section_id, $transaction->user_id);
            return [
                'message' => __('messages.syriatel_enrollment_success'),
            ];
        }
        if (!$viaCron)
            throw new \Exception(__('messages.syriatel_otp_failed'));
    }

    /**
     * Sends an OTP request to the customer's phone via SyriatelCash.
     *
     * @param  string  $phoneNumber    The customer's phone number (MSISDN).
     * @param  string  $transactionId  Unique transaction ID generated by the caller.
     * @param  float   $amount         The amount to be charged (e.g., section price after discount).
     * @return array                   Decoded JSON response from SyriatelCash on success.
     * @throws \Exception              Throws an exception with a user-friendly message on error.
     *
     * Possible "errorCode" values for sending OTP:
     *   0      => Success
     *  -3      => Invalid amount (negative or invalid characters)
     *  -7      => Merchant MSISDN is not active
     *  -10     => Merchant MSISDN does not have a merchant wallet
     *  -98     => Expired transaction (10 minutes)
     *  -99     => One or more parameters are null
     *  -100    => Technical error
     *  -101    => Duplicated transaction ID with different parameters
     *  -102    => The caller IP or merchant MSISDN is not defined
     *  -170    => The customer GSM is not allowed to pay during test phase
     *  -500    => The token is invalid
     */
    public function sendSyriatelCashOTP(string $phoneNumber, $transaction, float $amount): array
    {
        $token = $this->getToken();
        $response = $this->makePayment($token, $phoneNumber, $transaction, $amount);
        $responseData = json_decode($response, true);

        if (!isset($responseData['errorCode'])) {
            throw new \Exception(__('messages.syriatel_unexpected_response'));
        }

        if ($responseData['errorCode'] !== '0') {
            $message = $this->getReadableErrorMessage($responseData['errorCode']);
            throw new \Exception($message, 422);
        }
        $limitKey = 'otp-request-' . $phoneNumber;

        if (RateLimiter::tooManyAttempts($limitKey, 1)) {
            $secondsLeft = RateLimiter::availableIn($limitKey);

            return [
                'status' => 'otp_already_sent',
                'can_resend_after' => $secondsLeft,
            ];
        }

        $decaySeconds = 60;
        $shortIpKey = 'otp-request-ip:short:' . request()->ip();
        if (RateLimiter::tooManyAttempts($shortIpKey, 3)) {
            throw new \Exception(__("messages.too_many_requests", [
                'time' => $this->formatSeconds(RateLimiter::availableIn($shortIpKey)),
            ]), 429);

        }


        $longIpKey = 'otp-request-ip:long:' . request()->ip();
        if (RateLimiter::tooManyAttempts($longIpKey, 10)) {
            throw new \Exception(__("messages.too_many_requests", [
                'time' => $this->formatSeconds(RateLimiter::availableIn($longIpKey)),
            ]), 429);
        }
        RateLimiter::hit($longIpKey, 7200);
        RateLimiter::hit($shortIpKey, 60);
        RateLimiter::hit($limitKey, $decaySeconds);



        return $responseData;
    }




    protected function formatSeconds(int $seconds): string
    {
        if ($seconds < 60) {
            return __('messages.time.seconds', ['seconds' => $seconds]);
        }

        if ($seconds < 3600) {
            $minutes = ceil($seconds / 60);
            return __('messages.time.minutes', ['minutes' => $minutes]);
        }

        $hours = ceil($seconds / 3600);
        return __('messages.time.hours', ['hours' => $hours]);
    }

    /**
     * Checks the OTP via SyriatelCash for a given transaction.
     *
     * @param  string $otp
     * @param  string $transactionId
     * @return array  Decoded JSON response from SyriatelCash on success
     * @throws \Exception
     *
     * Possible "errorCode" values for checking OTP:
     *   0      => Success
     *  -6      => Customer MSISDN is not active
     *  -8      => Insufficient balance
     *  -13     => Customer MSISDN doesn’t have enough balance 
     *  -17     => Daily expenditure limit exceeded
     *  -96     => Invalid OTP
     *  -95     => Exceeded OTP tries (3 invalid attempts)
     *  -98     => Expired transaction (1 day)
     *  -99     => One or more parameters are null
     *  -100    => Technical error
     *  -101    => Duplicated transaction ID with different parameters
     *  -102    => The caller IP or merchant MSISDN is not defined
     *  -103    => Technical error in adding new merchant account
     *  -104    => Expired OTP
     *  -500    => The token is invalid
     */
    public function checkSyriatelCashOTP(string $otp, $transaction, $viaCron): array
    {
        $token = $this->getToken();
        $url = 'https://merchants.syriatel.sy:1443/ePayment_external_Json/rs/ePaymentExternalModule/paymentConfirmation';
        $payload = [
            'OTP' => $otp,
            'merchantMSISDN' => $this->merchantMSISDN,
            'transactionID' => $transaction->transaction_id,
            'token' => $token,
        ];

        $response = $this->makeCurlPost($url, $payload);
        $transaction->requests()->create([
            'api' => 'paymentConfirmation',
            'payload' => json_encode($payload),
            'response' => $response,
            'via_cron' => $viaCron,
        ]);
        $responseData = json_decode($response, true);
        if (!isset($responseData['errorCode'])) {
            throw new \Exception(__('messages.syriatel_unexpected_response'), 422);
        }

        if ($responseData['errorCode'] !== '0') {
            $transaction->update([
                'status' => PaymentTransaction::FAILED_STATUS,
            ]);
            $message = $this->getReadableErrorMessage($responseData['errorCode']);
            if (!$viaCron)
                throw new \Exception($message, 422);
        } else
            $transaction->update([
                'status' => PaymentTransaction::SUCCESS_STATUS,
            ]);

        return $responseData;
    }

    /**
     * Resends the OTP for a given transaction via the external API.
     *
     * @param  string $transactionId
     * @return array  Decoded JSON response on success
     * @throws \Exception
     *
     * Possible "errorCode" values for resend OTP:
     *   0      => Success
     *  -97     => Invalid or expired transaction
     *  -98     => Expired transaction (10 minutes have passed)
     *  -99     => One or more parameters are null
     *  -100    => Technical error
     *  -102    => the caller IP or merchant MSISDN is not defined
     *  -500    => The token is invalid
     */
    public function resendSyriatelCashOTP(string $transactionId): array
    {
        $transaction = PaymentTransaction::where('transaction_id', $transactionId)->firstOrFail();

        $limitKey = 'otp-request-' . $transaction->phone_number;
        if (RateLimiter::tooManyAttempts($limitKey, 1)) {
            throw new \Exception(__('messages.too_many_requests'), 422);
        }

        $token = $this->getToken();
        $url = 'https://merchants.syriatel.sy:1443/ePayment_external_Json/rs/ePaymentExternalModule/resendOTP';
        $payload = [
            'merchantMSISDN' => $this->merchantMSISDN,
            'transactionID' => $transactionId,
            'token' => $token,
        ];

        $response = $this->makeCurlPost($url, $payload);
        $transaction->requests()->create([
            'api' => 'resendOTP',
            'payload' => json_encode($payload),
            'response' => $response,
        ]);
        $responseData = json_decode($response, true);
        if (!isset($responseData['errorCode'])) {
            throw new \Exception(__('messages.syriatel_unexpected_response'), 422);
        }

        if ($responseData['errorCode'] !== '0') {
            $message = $this->getReadableErrorMessage($responseData['errorCode']);
            throw new \Exception($message, 422);
        }


        return $responseData;
    }

    /**
     * Retrieves and caches the token for 14 minutes.
     *
     * @return string
     * @throws \Exception
     */
    private function getToken(): string
    {
        return Cache::remember('syriatel_cash_token', 14 * 60, function () {
            $url = 'https://merchants.syriatel.sy:1443/ePayment_external_Json/rs/ePaymentExternalModule/getToken';
            $payload = [
                'username' => env('SYRIATEL_CASH_USERNAME'),
                'password' => env('SYRIATEL_CASH_PASSWORD'),
            ];

            $response = $this->makeCurlPost($url, $payload);
            $data = json_decode($response, true);

            if (empty($data['token'])) {
                throw new \Exception(
                    __("messages.syriatel_no_token", ['response' => $response])
                    ,
                    422
                );
            }

            return $data['token'];
        });
    }

    /**
     * Initiates a payment request (OTP send) via the external API.
     *
     * @param  string $token
     * @param  string $customerMSISDN
     * @param  string $transactionId
     * @param  float  $amount
     * @return string JSON-encoded response
     * @throws \Exception
     */
    private function makePayment(string $token, string $customerMSISDN, $transaction, float $amount)
    {
        $url = 'https://merchants.syriatel.sy:1443/ePayment_external_Json/rs/ePaymentExternalModule/paymentRequest';
        $payload = [
            'customerMSISDN' => $customerMSISDN,
            'merchantMSISDN' => $this->merchantMSISDN,
            'amount' => (string) $amount,
            'transactionID' => $transaction->transaction_id,
            'token' => $token,
        ];
        $response = $this->makeCurlPost($url, $payload);
        $transaction->requests()->create([
            'api' => 'paymentRequest',
            'payload' => json_encode($payload),
            'response' => $response,
        ]);
        return $response;
    }

    /**
     * Helper method to perform cURL POST requests.
     *
     * @param  string $url
     * @param  array  $payload
     * @return string JSON-encoded response from SyriatelCash
     * @throws \Exception
     */
    private function makeCurlPost(string $url, array $payload)
    {
        $curl = curl_init();

        curl_setopt_array($curl, [
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS => json_encode($payload),
            CURLOPT_HTTPHEADER => [
                'Content-Type: application/json',
                'User-Agent: Mozilla/5.0',
            ],
        ]);

        $response = curl_exec($curl);

        if (curl_errno($curl)) {
            $error = curl_error($curl);
            Log::error("cURL error: {$error}", ['url' => $url, 'payload' => $payload]);
            throw new \Exception(__("messages.syriatel_curl_error", ['error' => $error]), 422);
        }

        curl_close($curl);

        return $response;
    }

    /**
     * Maps SyriatelCash error codes to user-friendly messages (localized).
     *
     * @param  string|int $errorCode
     * @return string
     */
    private function getReadableErrorMessage($errorCode): string
    {
        $code = (string) $errorCode;


        $translationKey = "messages.syriatel_{$code}";

        if (\Lang::has($translationKey)) {
            return __($translationKey);
        }

        return __('messages.syriatel_unknown_error');
    }
}
